install-dependencies:
  image: node:22.4  # Using a standard Ubuntu-based Node image
  before_script:
    - apt-get update
    - apt-get install -y tree xvfb  # Install necessary dependencies
  script:
    - ls
    - pwd
    - npm install
    - cd svelte-tests && npm install
  artifacts:
    paths:
      - ./node_modules/
      - ./svelte-tests/node_modules/
      - ./svelte-tests/

run_tests:
  image: node:22.4  # Ubuntu-based Node image
  before_script:
    - apt-get update
    - apt-get install -y xvfb \
        libgtk-3-0 \
        libnotify-dev \
        libgconf-2-4 \
        libnss3 \
        libxss1 \
        libasound2 \
        libxtst6 \
        xauth \
        dbus \
        ttf-freefont \
        ca-certificates
    - npm install
    - cd svelte-tests && npm install
    - Xvfb :99 -screen 0 1280x1024x16 &  # Start xvfb
    - export DISPLAY=:99  # Set display to use xvfb
    - npm --version  # Ensure npm is installed
    - npx --version  # Ensure npx is installed
    - PORT=8080 npm run dev &  # Run the app in the background
    - sleep 10
  script:
    - cd svelte-tests && npx cypress run --e2e
  dependencies:
    - install-dependencies
