install-dependencies:
  image: node:22.4-bullseye-slim  # Using a standard Ubuntu-based Node image
  before_script:
    - apt-get update
    - apt-get install -y tree xvfb  # Install necessary dependencies
  script:
    - ls
    - pwd
    - npm install
    - cd svelte-tests && npm install
  artifacts:
    paths:
      - ./node_modules/
      - ./svelte-tests/node_modules/
      - ./svelte-tests/

run_tests:
  image: node:latest
  before_script:
    - apt-get update
    - npm --version  # Ensure npm is installed
    - npx --version  # Ensure npx is installed
    - PORT=8080 npm run dev &  # Run the app in the background
    - sleep 10
    - npm ci
    - npm start &
    - npm run e2e
# run_tests:
#   image: node:22.4-bullseye-slim  # Ubuntu-based Node image
#   before_script:
#     - apt-get update
#     - apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb
#     - npm install
#     - cd svelte-tests && npm install
#     - Xvfb :99 -screen 0 1280x1024x16 &  # Start xvfb
#     - export DISPLAY=:99  # Set display to use xvfb
#     - npm --version  # Ensure npm is installed
#     - npx --version  # Ensure npx is installed
#     - PORT=8080 npm run dev &  # Run the app in the background
#     - sleep 10
#   script:
#     - cd svelte-tests && npx cypress run --e2e
#   dependencies:
#     - install-dependencies
