install-dependencies:
  image: node:22.4-bullseye-slim  # Using a standard Ubuntu-based Node image
  before_script:
    - apt-get update
    - apt-get install -y tree xvfb  # Install necessary dependencies
  script:
    - ls
    - pwd
    - npm install
    - cd svelte-tests && npm install
  artifacts:
    paths:
      - ./node_modules/
      - ./svelte-tests/node_modules/
      - ./svelte-tests/

variables:
  TZ: "Asia/Kolkata"  
  
run_tests:
  image: node:latest
  before_script:
    - npm install
    - cd svelte-tests/ && npm install
    - cd ..
    - apt-get update  # Update the package lists
    - apt-get install -y libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth xvfb  # Install dependencies
    - Xvfb :99 -screen 0 1280x1024x16 &  # Start virtual framebuffer for headless testing
    - export DISPLAY=:99  # Set the display for Xvfb
    - npm --version  # Ensure npm is installed
    - npx --version  # Ensure npx is installed
    - PORT=8080 npm run dev &  # Run the app in the background
    - sleep 10  # Give the app time to start
    - curl --retry 10 --retry-delay 5 -I http://localhost:8080 || exit 1
  script:
    - cd svelte-tests
    - npm ci
    - npx cypress run --e2e
