install-dependencies:
  image: node:22.4-alpine
  before_script:
    - apk update
    - apk add tree
    - apk add xvfb
  script:
    - ls
    - pwd
    - npm install
    - cd svelte-tests && npm install
  artifacts:
    paths:
      - ./node_modules/
      - ./svelte-tests/node_modules/
      - ./svelte-tests/

run_tests:
  image: node:22.4-alpine
  before_script:
    - apk update
    - apk add xvfb libgtk-3.0 gcompat \
        chromium \
        nss \
        harfbuzz \
        ca-certificates \
        ttf-freefont \
        ffmpeg \
        dbus \
        alsa-lib \
        eudev \
        udev
    - apk add xvfb  # Install xvfb for headless browser
    - Xvfb :99 -screen 0 1280x1024x16 &  # Start xvfb
    - export DISPLAY=:99  # Set display to use xvfb
    - npm --version  # Ensure npm is installed
    - npx --version  # Ensure npx is installed
    - PORT=8080 npm run dev &  # Run the app in the background
    - sleep 10
  script:
    - cd svelte-tests && npx cypress run --e2e 
  dependencies:
    - install-dependencies 